# Generated by Django 3.2 on 2021-04-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_auto_20151226_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesstype',
            options={'ordering': ['label'], 'verbose_name': 'Access Type', 'verbose_name_plural': 'Access Types'},
        ),
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ['owner__lname', 'owner__fname', 'atype__label'], 'verbose_name': 'Grant', 'verbose_name_plural': 'Grants'},
        ),
        migrations.AlterModelOptions(
            name='nonmembertoken',
            options={'ordering': ['contact', 'ttype__label'], 'verbose_name': 'Non-member token', 'verbose_name_plural': 'Non-member tokens'},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['owner__lname', 'owner__fname', 'ttype__label'], 'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
        migrations.AlterModelOptions(
            name='tokentype',
            options={'ordering': ['label'], 'verbose_name': 'Token Type', 'verbose_name_plural': 'Token Types'},
        ),
    ]
