# Generated by Django 3.2 on 2021-04-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndaparser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.DateTimeField(verbose_name='Datetime')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='Name')),
                ('reference', models.CharField(max_length=200, verbose_name='Reference')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount')),
                ('unique_id', models.CharField(max_length=64, verbose_name='Unique transaction id')),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
    ]
